[project]
name = "crypto-data-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rafaelmotafreitas", email = "rafaelmotta200@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
crypto-data-pipeline = "crypto_data_pipeline:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
